ALTER TABLE MMS_DOCUMENT  RENAME COLUMN  QTY  TO QTY_TEMP;
ALTER TABLE MMS_DOCUMENT  ADD QTY  NUMBER(38, 4);
UPDATE MMS_DOCUMENT SET QTY = TRIM(QTY_TEMP);
ALTER TABLE MMS_DOCUMENT DROP COLUMN QTY_TEMP;

ALTER TABLE MMS_DOCUMENT  RENAME COLUMN  HANDLED_QTY  TO HANDLED_QTY_TEMP;
ALTER TABLE MMS_DOCUMENT  ADD HANDLED_QTY  NUMBER(38, 4);
UPDATE MMS_DOCUMENT SET HANDLED_QTY = TRIM(HANDLED_QTY_TEMP);
ALTER TABLE MMS_DOCUMENT DROP COLUMN HANDLED_QTY_TEMP;

ALTER TABLE MMS_DOCUMENT  RENAME COLUMN  UN_HANDLE_QTY  TO UN_HANDLE_QTY_TEMP;
ALTER TABLE MMS_DOCUMENT  ADD UN_HANDLE_QTY  NUMBER(38, 4);
UPDATE MMS_DOCUMENT SET UN_HANDLE_QTY = TRIM(UN_HANDLE_QTY_TEMP);
ALTER TABLE MMS_DOCUMENT DROP COLUMN UN_HANDLE_QTY_TEMP;

ALTER TABLE MMS_DOCUMENT  RENAME COLUMN  RESERVED_QTY  TO RESERVED_QTY_TEMP;
ALTER TABLE MMS_DOCUMENT  ADD RESERVED_QTY  NUMBER(38, 4);
UPDATE MMS_DOCUMENT SET RESERVED_QTY = TRIM(RESERVED_QTY_TEMP);
ALTER TABLE MMS_DOCUMENT DROP COLUMN RESERVED_QTY_TEMP;

ALTER TABLE MMS_DOCUMENT  RENAME COLUMN  UN_RESERVED_QTY  TO UN_RESERVED_QTY_TEMP;
ALTER TABLE MMS_DOCUMENT  ADD UN_RESERVED_QTY  NUMBER(38, 4);
UPDATE MMS_DOCUMENT SET UN_RESERVED_QTY = TRIM(UN_RESERVED_QTY_TEMP);
ALTER TABLE MMS_DOCUMENT DROP COLUMN UN_RESERVED_QTY_TEMP;


ALTER TABLE MMS_DOCUMENT_HIS  RENAME COLUMN  QTY  TO QTY_TEMP;
ALTER TABLE MMS_DOCUMENT_HIS  ADD QTY  NUMBER(38, 4);
UPDATE MMS_DOCUMENT_HIS SET QTY = TRIM(QTY_TEMP);
ALTER TABLE MMS_DOCUMENT_HIS DROP COLUMN QTY_TEMP;

ALTER TABLE MMS_DOCUMENT_HIS  RENAME COLUMN  HANDLED_QTY  TO HANDLED_QTY_TEMP;
ALTER TABLE MMS_DOCUMENT_HIS  ADD HANDLED_QTY  NUMBER(38, 4);
UPDATE MMS_DOCUMENT_HIS SET HANDLED_QTY = TRIM(HANDLED_QTY_TEMP);
ALTER TABLE MMS_DOCUMENT_HIS DROP COLUMN HANDLED_QTY_TEMP;

ALTER TABLE MMS_DOCUMENT_HIS  RENAME COLUMN  UN_HANDLE_QTY  TO UN_HANDLE_QTY_TEMP;
ALTER TABLE MMS_DOCUMENT_HIS  ADD UN_HANDLE_QTY  NUMBER(38, 4);
UPDATE MMS_DOCUMENT_HIS SET UN_HANDLE_QTY = TRIM(UN_HANDLE_QTY_TEMP);
ALTER TABLE MMS_DOCUMENT_HIS DROP COLUMN UN_HANDLE_QTY_TEMP;

ALTER TABLE MMS_DOCUMENT_HIS  RENAME COLUMN  RESERVED_QTY  TO RESERVED_QTY_TEMP;
ALTER TABLE MMS_DOCUMENT_HIS  ADD RESERVED_QTY  NUMBER(38, 4);
UPDATE MMS_DOCUMENT_HIS SET RESERVED_QTY = TRIM(RESERVED_QTY_TEMP);
ALTER TABLE MMS_DOCUMENT_HIS DROP COLUMN RESERVED_QTY_TEMP;

ALTER TABLE MMS_DOCUMENT_HIS  RENAME COLUMN  UN_RESERVED_QTY  TO UN_RESERVED_QTY_TEMP;
ALTER TABLE MMS_DOCUMENT_HIS  ADD UN_RESERVED_QTY  NUMBER(38, 4);
UPDATE MMS_DOCUMENT_HIS SET UN_RESERVED_QTY = TRIM(UN_RESERVED_QTY_TEMP);
ALTER TABLE MMS_DOCUMENT_HIS DROP COLUMN UN_RESERVED_QTY_TEMP;