ALTER TABLE MMS_MATERIAL_LOT_INVENTORY  RENAME COLUMN  STOCK_QTY  TO STOCK_QTY_TEMP;
ALTER TABLE MMS_MATERIAL_LOT_INVENTORY  ADD STOCK_QTY  NUMBER(38, 4);
UPDATE MMS_MATERIAL_LOT_INVENTORY SET STOCK_QTY = TRIM(STOCK_QTY_TEMP);
ALTER TABLE MMS_MATERIAL_LOT_INVENTORY DROP COLUMN STOCK_QTY_TEMP;