ALTER TABLE MMS_MATERIAL_LOT  RENAME COLUMN  RECEIVE_QTY  TO RECEIVE_QTY_TEMP;
ALTER TABLE MMS_MATERIAL_LOT  ADD RECEIVE_QTY  NUMBER(38, 4);
UPDATE MMS_MATERIAL_LOT SET RECEIVE_QTY = TRIM(RECEIVE_QTY_TEMP);
ALTER TABLE MMS_MATERIAL_LOT DROP COLUMN RECEIVE_QTY_TEMP;

ALTER TABLE MMS_MATERIAL_LOT  RENAME COLUMN  CURRENT_QTY  TO CURRENT_QTY_TEMP;
ALTER TABLE MMS_MATERIAL_LOT  ADD CURRENT_QTY  NUMBER(38, 4);
UPDATE MMS_MATERIAL_LOT SET CURRENT_QTY = TRIM(CURRENT_QTY_TEMP);
ALTER TABLE MMS_MATERIAL_LOT DROP COLUMN CURRENT_QTY_TEMP;

ALTER TABLE MMS_MATERIAL_LOT  RENAME COLUMN  RESERVED_QTY  TO RESERVED_QTY_TEMP;
ALTER TABLE MMS_MATERIAL_LOT  ADD RESERVED_QTY  NUMBER(38, 4);
UPDATE MMS_MATERIAL_LOT SET RESERVED_QTY = TRIM(RESERVED_QTY_TEMP);
ALTER TABLE MMS_MATERIAL_LOT DROP COLUMN RESERVED_QTY_TEMP;

ALTER TABLE MMS_MATERIAL_LOT_HIS  RENAME COLUMN  RECEIVE_QTY  TO RECEIVE_QTY_TEMP;
ALTER TABLE MMS_MATERIAL_LOT_HIS  ADD RECEIVE_QTY  NUMBER(38, 4);
UPDATE MMS_MATERIAL_LOT_HIS SET RECEIVE_QTY = TRIM(RECEIVE_QTY_TEMP);
ALTER TABLE MMS_MATERIAL_LOT_HIS DROP COLUMN RECEIVE_QTY_TEMP;

ALTER TABLE MMS_MATERIAL_LOT_HIS  RENAME COLUMN  CURRENT_QTY  TO CURRENT_QTY_TEMP;
ALTER TABLE MMS_MATERIAL_LOT_HIS  ADD CURRENT_QTY  NUMBER(38, 4);
UPDATE MMS_MATERIAL_LOT_HIS SET CURRENT_QTY = TRIM(CURRENT_QTY_TEMP);
ALTER TABLE MMS_MATERIAL_LOT_HIS DROP COLUMN CURRENT_QTY_TEMP;

ALTER TABLE MMS_MATERIAL_LOT_HIS  RENAME COLUMN  RESERVED_QTY  TO RESERVED_QTY_TEMP;
ALTER TABLE MMS_MATERIAL_LOT_HIS  ADD RESERVED_QTY  NUMBER(38, 4);
UPDATE MMS_MATERIAL_LOT_HIS SET RESERVED_QTY = TRIM(RESERVED_QTY_TEMP);
ALTER TABLE MMS_MATERIAL_LOT_HIS DROP COLUMN RESERVED_QTY_TEMP;