/**
 * 更新Vanchip的MMS_MARTERIAL表栏位
 */

comment on column MMS_MATERIAL.RESERVED1 is '大类描述';
comment on column MMS_MATERIAL.RESERVED2 is '中类描述';
comment on column MMS_MATERIAL.RESERVED3 is '中类/物料组';
comment on column MMS_MATERIAL.RESERVED4 is '小类描述';
comment on column MMS_MATERIAL.RESERVED5 is '客户产品型号';
comment on column MMS_MATERIAL.RESERVED6 is '客户产品版本';
comment on column MMS_MATERIAL.RESERVED7 is '客户物料代码';
comment on column MMS_MATERIAL.RESERVED8 is '封装厂';
comment on column MMS_MATERIAL.RESERVED9 is '是否保税';
comment on column MMS_MATERIAL.RESERVED10 is 'HS 编码';
comment on column MMS_MATERIAL.RESERVED11 is '产品尺寸';
comment on column MMS_MATERIAL.RESERVED12 is '所属部门';
comment on column MMS_MATERIAL.RESERVED13 is '客户代码';
comment on column MMS_MATERIAL.RESERVED14 is '客户简称';
comment on column MMS_MATERIAL.RESERVED15 is '客户全称';
comment on column MMS_MATERIAL.RESERVED16 is '物料属性';
comment on column MMS_MATERIAL.RESERVED17 is '采购单位';
comment on column MMS_MATERIAL.RESERVED18 is '供应商';
comment on column MMS_MATERIAL.RESERVED19 is '备件价格';
comment on column MMS_MATERIAL.RESERVED20 is '内部编码';
comment on column MMS_MATERIAL.RESERVED21 is '是否特殊备件';
comment on column MMS_MATERIAL.RESERVED22 is '规格型号';
comment on column MMS_MATERIAL.RESERVED23 is '图纸';
comment on column MMS_MATERIAL.RESERVED24 is '备件KIT回填ERP物料代码';
comment on column MMS_MATERIAL.RESERVED25 is 'Remark';
comment on column MMS_MATERIAL.RESERVED26 is 'ABC标识';
comment on column MMS_MATERIAL.RESERVED27 is '批次管理标识';
comment on column MMS_MATERIAL.RESERVED28 is '机器类别';
comment on column MMS_MATERIAL.RESERVED29 is '交付周期';

comment on column MMS_MATERIAL_HIS.RESERVED1 is '大类描述';
comment on column MMS_MATERIAL_HIS.RESERVED2 is '中类描述';
comment on column MMS_MATERIAL_HIS.RESERVED3 is '中类/物料组';
comment on column MMS_MATERIAL_HIS.RESERVED4 is '小类描述';
comment on column MMS_MATERIAL_HIS.RESERVED5 is '客户产品型号';
comment on column MMS_MATERIAL_HIS.RESERVED6 is '客户产品版本';
comment on column MMS_MATERIAL_HIS.RESERVED7 is '客户物料代码';
comment on column MMS_MATERIAL_HIS.RESERVED8 is '封装厂';
comment on column MMS_MATERIAL_HIS.RESERVED9 is '是否保税';
comment on column MMS_MATERIAL_HIS.RESERVED10 is 'HS 编码';
comment on column MMS_MATERIAL_HIS.RESERVED11 is '产品尺寸';
comment on column MMS_MATERIAL_HIS.RESERVED12 is '所属部门';
comment on column MMS_MATERIAL_HIS.RESERVED13 is '客户代码';
comment on column MMS_MATERIAL_HIS.RESERVED14 is '客户简称';
comment on column MMS_MATERIAL_HIS.RESERVED15 is '客户全称';
comment on column MMS_MATERIAL_HIS.RESERVED16 is '物料属性';
comment on column MMS_MATERIAL_HIS.RESERVED17 is '采购单位';
comment on column MMS_MATERIAL_HIS.RESERVED18 is '供应商';
comment on column MMS_MATERIAL_HIS.RESERVED19 is '备件价格';
comment on column MMS_MATERIAL_HIS.RESERVED20 is '内部编码';
comment on column MMS_MATERIAL_HIS.RESERVED21 is '是否特殊备件';
comment on column MMS_MATERIAL_HIS.RESERVED22 is '规格型号';
comment on column MMS_MATERIAL_HIS.RESERVED23 is '图纸';
comment on column MMS_MATERIAL_HIS.RESERVED24 is '备件KIT回填ERP物料代码';
comment on column MMS_MATERIAL_HIS.RESERVED25 is 'Remark';
comment on column MMS_MATERIAL_HIS.RESERVED26 is 'ABC标识';
comment on column MMS_MATERIAL_HIS.RESERVED27 is '批次管理标识';
comment on column MMS_MATERIAL_HIS.RESERVED28 is '机器类别';
comment on column MMS_MATERIAL_HIS.RESERVED29 is '交付周期';